export type Mission = {
  id: number;
  description: string;
  category: "conversation" | "action" | "social" | "piège";
  difficulty: "easy" | "medium" | "hard";
};

export const MISSIONS: Mission[] = [
  { id: 1, description: "Fais dire le mot \"pastèque\" à ta cible", category: "conversation", difficulty: "medium" },
  { id: 2, description: "Fais dire le mot \"parapluie\" à ta cible", category: "conversation", difficulty: "medium" },
  { id: 3, description: "Fais dire \"je suis fatigué(e)\" à ta cible", category: "conversation", difficulty: "easy" },
  { id: 4, description: "Fais dire le mot \"dinosaure\" à ta cible", category: "conversation", difficulty: "hard" },
  { id: 5, description: "Fais dire le mot \"Madagascar\" à ta cible", category: "conversation", difficulty: "hard" },
  { id: 6, description: "Fais dire \"c'est pas faux\" à ta cible", category: "conversation", difficulty: "medium" },
  { id: 7, description: "Fais dire le mot \"chaussette\" à ta cible", category: "conversation", difficulty: "hard" },
  { id: 8, description: "Fais dire le mot \"barbecue\" à ta cible", category: "conversation", difficulty: "easy" },
  { id: 9, description: "Fais dire \"j'ai faim\" à ta cible", category: "conversation", difficulty: "easy" },
  { id: 10, description: "Fais dire le mot \"trampoline\" à ta cible", category: "conversation", difficulty: "hard" },
  { id: 11, description: "Fais dire le mot \"chocolat\" à ta cible", category: "conversation", difficulty: "easy" },
  { id: 12, description: "Fais dire \"attends deux secondes\" à ta cible", category: "conversation", difficulty: "easy" },
  { id: 13, description: "Fais dire le mot \"koala\" à ta cible", category: "conversation", difficulty: "hard" },
  { id: 14, description: "Fais dire le mot \"Netflix\" à ta cible", category: "conversation", difficulty: "easy" },
  { id: 15, description: "Fais dire le mot \"gratin\" à ta cible", category: "conversation", difficulty: "medium" },
  { id: 16, description: "Fais dire le mot \"fromage\" à ta cible", category: "conversation", difficulty: "easy" },
  { id: 17, description: "Fais dire \"je te jure\" à ta cible", category: "conversation", difficulty: "easy" },
  { id: 18, description: "Fais dire le mot \"volcan\" à ta cible", category: "conversation", difficulty: "hard" },
  { id: 19, description: "Fais dire le mot \"Espagne\" à ta cible", category: "conversation", difficulty: "medium" },
  { id: 20, description: "Fais dire \"c'est chaud\" à ta cible", category: "conversation", difficulty: "easy" },
  { id: 21, description: "Fais trinquer avec ta cible", category: "action", difficulty: "easy" },
  { id: 22, description: "Fais faire un high five à ta cible", category: "action", difficulty: "easy" },
  { id: 23, description: "Fais prendre une photo de toi par ta cible", category: "action", difficulty: "medium" },
  { id: 24, description: "Fais croiser les bras à ta cible", category: "action", difficulty: "medium" },
  { id: 25, description: "Fais boire un verre d'eau à ta cible", category: "action", difficulty: "easy" },
  { id: 26, description: "Fais applaudir ta cible", category: "action", difficulty: "medium" },
  { id: 27, description: "Fais se lever ta cible (si elle est assise)", category: "action", difficulty: "easy" },
  { id: 28, description: "Fais mettre les mains dans les poches à ta cible", category: "action", difficulty: "medium" },
  { id: 29, description: "Fais ouvrir une porte à ta cible (galanterie)", category: "action", difficulty: "medium" },
  { id: 30, description: "Fais ramasser un objet au sol par ta cible", category: "action", difficulty: "medium" },
  { id: 31, description: "Fais chanter ta cible (même 2 secondes)", category: "action", difficulty: "hard" },
  { id: 32, description: "Fais danser ta cible (même un petit pas)", category: "action", difficulty: "hard" },
  { id: 33, description: "Fais porter un objet à ta cible pendant 30 secondes", category: "action", difficulty: "medium" },
  { id: 34, description: "Fais asseoir ta cible à ta place", category: "action", difficulty: "medium" },
  { id: 35, description: "Fais tourner ta cible sur elle-même", category: "action", difficulty: "hard" },
  { id: 36, description: "Fais raconter une blague à ta cible", category: "social", difficulty: "medium" },
  { id: 37, description: "Fais complimenter quelqu'un d'autre par ta cible", category: "social", difficulty: "medium" },
  { id: 38, description: "Fais raconter un souvenir d'enfance à ta cible", category: "social", difficulty: "medium" },
  { id: 39, description: "Fais recommander un film par ta cible", category: "social", difficulty: "easy" },
  { id: 40, description: "Fais parler de son plat préféré à ta cible", category: "social", difficulty: "easy" },
  { id: 41, description: "Fais montrer une photo de son téléphone par ta cible", category: "social", difficulty: "medium" },
  { id: 42, description: "Fais deviner ton âge par ta cible", category: "social", difficulty: "easy" },
  { id: 43, description: "Fais dire un mot dans une autre langue à ta cible", category: "social", difficulty: "medium" },
  { id: 44, description: "Fais parler de sa série préférée à ta cible", category: "social", difficulty: "easy" },
  { id: 45, description: "Fais imiter quelqu'un par ta cible", category: "social", difficulty: "hard" },
  { id: 46, description: "Fais présenter quelqu'un par ta cible", category: "social", difficulty: "medium" },
  { id: 47, description: "Fais donner un conseil à ta cible", category: "social", difficulty: "easy" },
  { id: 48, description: "Fais raconter un rêve (même inventé) à ta cible", category: "social", difficulty: "hard" },
  { id: 49, description: "Fais parler de son artiste préféré à ta cible", category: "social", difficulty: "easy" },
  { id: 50, description: "Fais dire un truc positif sur quelqu'un par ta cible", category: "social", difficulty: "easy" },
  { id: 51, description: "Fais vérifier l'heure par ta cible", category: "piège", difficulty: "easy" },
  { id: 52, description: "Fais te passer un objet (sel, téléphone...) par ta cible", category: "piège", difficulty: "easy" },
  { id: 53, description: "Fais se retourner ta cible (\"regarde derrière toi\")", category: "piège", difficulty: "easy" },
  { id: 54, description: "Fais goûter quelque chose par ta cible", category: "piège", difficulty: "medium" },
  { id: 55, description: "Fais sentir quelque chose par ta cible", category: "piège", difficulty: "medium" },
  { id: 56, description: "Fais bâiller ta cible (le bâillement est contagieux...)", category: "piège", difficulty: "hard" },
  { id: 57, description: "Fais rire ta cible (un vrai rire, pas juste un sourire)", category: "piège", difficulty: "medium" },
  { id: 58, description: "Fais prêter un objet par ta cible", category: "piège", difficulty: "easy" },
  { id: 59, description: "Fais serrer la main à ta cible", category: "piège", difficulty: "medium" },
  { id: 60, description: "Fais regarder ton téléphone par ta cible (lui montrer un truc)", category: "piège", difficulty: "easy" },
  { id: 61, description: "Fais chuchoter ta cible", category: "piège", difficulty: "hard" },
  { id: 62, description: "Fais compter quelque chose à ta cible", category: "piège", difficulty: "medium" },
  { id: 63, description: "Fais fermer les yeux à ta cible (\"devine ce que c'est\")", category: "piège", difficulty: "hard" },
  { id: 64, description: "Fais toucher ses cheveux à ta cible", category: "piège", difficulty: "hard" },
  { id: 65, description: "Fais soupirer ta cible", category: "piège", difficulty: "medium" },
];

export function getMissionById(id: number): Mission | undefined {
  return MISSIONS.find((m) => m.id === id);
}
